#!/bin/bash

# TODO: Make sure clone and pull operations minimize the history downloaded

RED='\033[0;31m'
NC='\033[0m'

# Function to display usage
usage() {
    cat << EOF
Usage: ./spu [-s|--update-spu]
       ./spu [-b|--update-baseline] [-o|--offline] [-v|--verify] [(<path to manuals.txt> <path to versions.txt>)]
       ./spu [-i|--init]
EOF
    exit 1
}

error_exit() {
    echo -e "${RED}$1${NC}" >&2
    exit 1
}

update_spu() {
    echo "Pulling SPU from remote repository..."
    git pull origin main
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to update SPU. Please check your network connection and try again.${NC}"
        exit 1
    fi
    echo "SPU updated successfully."
    exit 0
}

init_baseline() {
    if [ -d "baseline" ]; then
        echo -e "${RED}baseline directory already exists.${NC}"
        exit 1
    fi
    if [ ! -f "init_url.txt" ]; then
        echo -e "${RED}Init file init_url.txt does not exist.${NC}"
        exit 1
    fi
    echo "Cloning baseline..."
    git clone $(head -n 1 "init_url.txt") baseline
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to clone baseline. Check your internet connection.${NC}"
        exit 1
    fi
    exit 0
}

# Check to make sure spu is run from the root of the SPU repository
if [ "$0" != "./spu" ]; then
    echo -e "${RED}Please run SPU from the root of the SPU repository (./spu)${NC}"
    exit 1
fi

# Check for git
if ! command -v git &> /dev/null; then
    echo -e "${RED}git is not installed.${NC}"
    exit 1
fi

# Initialize variables
UPDATE_BASELINE=false
OFFLINE=false
VERIFY=false
MANUALS_FILE="baseline/manuals.txt"
VERSIONS_FILE="baseline/versions.txt"

# Parse options
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  -s | --update-spu )
    update_spu
    ;;
  -i | --init )
    init_baseline
    ;;
  -b | --update-baseline )
    UPDATE_BASELINE=true
    ;;
  -o | --offline )
    OFFLINE=true
    ;;
  -v | --verify )
    VERIFY=true
    ;;
  * )
    usage
    ;;
esac; shift; done
if [[ "$1" == '--' ]]; then shift; fi

# Parse manuals and versions arguments
if [ $# -eq 2 ]; then
    MANUALS_FILE=$1
    VERSIONS_FILE=$2
elif [ $# -ne 0 ]; then
    usage
fi

# Check for baseline update option
if [[ "$UPDATE_BASELINE" == true && "$OFFLINE" == false ]]; then
    echo "Updating baseline..."
    cd baseline
    BASELINE_URL=$(grep "^baseline .*$" "$MANUALS_FILE" | cut -d' ' -f2)
    git checkout -f main
    # TODO: Check to see if the URL has changed. Likely need to clone if so, or limit migration.
    git remote set-url origin "$BASELINE_URL"
    git pull origin main
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to update baseline. Please check your network connection and try again.${NC}"
        cd ..
        exit 1
    fi
    cd ..
fi

# Verify that both manuals and versions exist
if [ ! -f "$MANUALS_FILE" ]; then
    echo -e "${RED}Manuals file not found: ${MANUALS_FILE}${NC}"
    exit 1
fi
if [ ! -f "$VERSIONS_FILE" ]; then
    echo -e "${RED}Versions file not found: ${VERSIONS_FILE}${NC}"
    exit 1
fi

echo "Updating manuals using manuals: $MANUALS_FILE with versions: $VERSIONS_FILE"
echo

# Creates the pubs directory
PUBS_DIR="pubs"
mkdir -p "$PUBS_DIR"

# List out all of the manuals to download
PUBS=$(cut -d' ' -f1 "$VERSIONS_FILE")

# Update each manual
for PUB in $PUBS; do
    # Get the desired version and URL for the manual
    VERSION=$(grep "^$PUB .*$" "$VERSIONS_FILE" | cut -d' ' -f2)
    REPO_URL=$(grep "^$PUB .*$" "$MANUALS_FILE" | cut -d' ' -f2)
    if [ "$REPO_URL" == "" ]; then
        echo -e "${RED}No URL found for ${PUB}${NC}"
        echo
        continue
    fi

    if [ "$OFFLINE" == false ]; then
        if [ -d "$PUBS_DIR/$PUB" ]; then
            # Directory exists, fetch changes and checkout the desired version
            # TODO: Perform similar URL change/check that baseline performs?
            echo "Updating $PUBS_DIR/$PUB"
            cd "$PUBS_DIR/$PUB"
            git checkout -f main
            git fetch -f --tags
            git pull origin main
            cd ../..
        else
            # Directory does not exist, clone the repo
            echo "Cloning $PUB"
            git clone "$REPO_URL" "$PUBS_DIR/$PUB"
        fi
    else
        echo "Skipping online update for $PUB"
    fi

    # Verify the directory exists
    if [ ! -d "$PUBS_DIR/$PUB" ]; then
        echo -e "${RED}Directory for $PUB does not exist${NC}"
        echo
        continue
    fi

    cd "$PUBS_DIR/$PUB"
    if [ -z "$(git tag --list "$VERSION")" ]; then
        # No version specified, use the latest
        echo -e "${RED}No version $VERSION found for ${PUB}, using most recent commit${NC}"
    else
        # Checkout the desired version
        echo "Using version $VERSION for $PUB"
        git config advice.detachedHead false
        git checkout -f "$VERSION"
    fi
    cd ../..
    echo
done

# Verify the versions of all downloaded manuals
if [ "$VERIFY" == true ]; then
    echo "Verifying versions..."
    echo ""
    cd "$PUBS_DIR"
    for PUB in "$PUBS"; do
        cd "$PUB"
        echo "$PUB"
        git log --oneline --decorate -n 1 HEAD
        cd ..
    done
    cd ..
fi
