name: Test SPU Script

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bats

      - name: Make script executable
        run: chmod +x spu

      - name: Run Bats tests
        run: bats tests